### ISSUE TITLE
Memory Leak in NG2AgGrid

### ISSUE THREAD

**Issue by hjunaid** [ag-grid/ag-grid-angular#102]
There seems to be a memory leak in either the wrapper or the underlying component. The component is subscribing to lots of events leaving one/few not being released on ngOnDestroy().

Steps to recreate the leak:

- Create two routes in the application one for the Grid (/grid) and the other for home page. Instantiate an empty AgGrid in /grid route 
- Navigate to /grid route and then back to home route 
- Take a Heap Snapshot and search for AgGrid. The instance will still be there. 

Can you please investigate which subscriber is not being cleaned on ngOnDestory ?

**Comment by hjunaid** [comment]
Update: I have tested it with underlying component and there is no leak in it. So, most likely the wrapper is leaking eventlisteners. 

Perhaps this function is worth investigating. 

file:agGridNg2.ts 
  ```
  private createComponentEvents() {
        ComponentUtil.EVENTS.forEach((eventName) => {
            (<any>this)[eventName] = new EventEmitter();
        });
    }

```
Should ngOnDestory() clear up all these EventEmitters?

**Comment by seanlandsman** [comment]
hi

Thanks for reporting this - I'll investigate and see what I can find

Thanks!

**Comment by rmullins9** [comment]
this is actually a memory leak in Angular2. I have a bug open with them. The issue is that NO injected services are being destroyed (including the router, etc). If you look in their code when you destroy a component ref, there is a TODO to destroy the zone which i think should let the DI clean up.

**Comment by seanlandsman** [comment]
@rmullins9 thanks for this - do you have a link to the angular issue?

**Comment by jskrzypek** [comment]
https://github.com/angular/angular/issues/13725

**Comment by seanlandsman** [comment]
thanks @jskrzypek

**Comment by dereklin** [comment]
I have created a repo with ag-grid refreshing about every second.  Eventually Chrome will crash saying it has run out of memeory: https://github.com/dereklin/ng-ws-ngrx-ag-grid

Is there a workaround?

**Comment by rokkuci** [comment]
Hey, guys it is serious issue. Any suggestions how to solve it?

**Comment by mischkl** [comment]
Still happening with ng4 and ag-grid 11

**Comment by seanlandsman** [comment]
@rokkuci this is an issue on angular's side - we cannot do anything about it and depend on https://github.com/angular/angular/issues/13725 being fixed to resolve this
