### ISSUE TITLE
Custom editor inside ag-grid

### ISSUE THREAD

**Issue by SatyabratKumarSingh** [ag-grid/ag-grid-angular#131]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Ideally grid should be able to render a custom editor inside a cell.

**Expected behavior**

The custom editor is not rendered ( I cant see drop down expansion) when I put it inside the ag-grid.

Here is my code : 

    import { Component, ViewContainerRef, ViewChild, AfterViewInit } from '@angular/core';
    import { ICellEditorAngularComp } from 'ag-grid-angular/main';
    import { RegionProductsConfigService } from '../region-product-config.service';
    @Component({
     selector: 'ag-product-editor-control',
     template: `             
          <ng-select #multiselect
                [options]="products"
                [multiple]="true"
                placeholder="Select multiple"                
                (opened)="onMultipleOpened()"
                (closed)="onMultipleClosed()"                      
                (selected)="onMultipleSelected($event)"
                (deselected)="onMultipleDeselected($event)">
            </ng-select>        
    `,
    providers: [RegionProductsConfigService],
     
    })
    export class ProductEditorComponent implements ICellEditorAngularComp, AfterViewInit {
      products: Array<any>;
      item: any;
      @ViewChild('multiselect', { read: ViewContainerRef }) private container;
       ngAfterViewInit() {
         this.container.element.nativeElement.focus();
    }
    onMultipleOpened() {

    }

    onMultipleClosed() {

    }

    onMultipleSelected(item) {
        this.item = item;
    }

    onMultipleDeselected(item) {

    }

    agInit(params: any): void {
        this.products = RegionProductsConfigService.getProducts().map(x => ({ 'value': x.ID, 'label': x.Name }));       
    }
    getValue(): any {
        return this.item;
    }
    isPopup(): boolean {
        return true;
    }    
}

But I dont see the dropdown items. What could be the reason?

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-angular version:** 2.0.X

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by SatyabratKumarSingh** [comment]
![image](https://cloud.githubusercontent.com/assets/8794283/23173967/c8ec6296-f852-11e6-83b2-9832db2244a5.png)

**Comment by SatyabratKumarSingh** [comment]
I wanted the behavior on the top image inside the grid.

**Comment by seanlandsman** [comment]
The grid does indeed support custom editors - take a look at 

https://www.ag-grid.com/javascript-grid-cell-editing
https://www.ag-grid.com/javascript-grid-cell-editor/angular.php

Also take a look at the examples provided in the example repo: https://github.com/ceolter/ag-grid-angular-example

**Comment by SatyabratKumarSingh** [comment]
Hi,
I did the same but unfortunately couldn't get it working..It doesn't expand the drop down..Is this controlled by isPopup?

**Comment by shrutika-dasgupta** [comment]
Was this resolved??

**Comment by SatyabratKumarSingh** [comment]
yes.. I can send code if you need.

**Comment by sxm21** [comment]
@SatyabratKumarSingh  what was your solution?

**Comment by seanlandsman** [comment]
f

**Comment by majoshi1** [comment]
Hi Satyabrat,

I am also facing same problem.
Can you please share your code / fix ?
For now, I am back to the built-in dropdown.

		cellEditor: 'select',
                cellEditorParams: {
                    values: ['1 First', '2 Second'],
                },
                newValueHandler: p => {console.log("oldValue:"+p.oldValue+", newValue:"+p.newValue);}

**Comment by anitvm** [comment]
Hi @SatyabratKumarSingh / @majoshi1 
  I am also facing the same issue. It would be great if you can share your solution.
Thank You

**Comment by seanlandsman** [comment]
Popup and dropdown editors are provided in our examples repo here: https://github.com/ceolter/ag-grid-angular-example and here: https://github.com/seanlandsman/ag-grid-angular-third-party-example

**Comment by smile2014** [comment]
@SatyabratKumarSingh  I am also facing the same issue. It would be great if you can share your solution.
Thank You

**Comment by ilmagowalter** [comment]
@SatyabratKumarSingh 
can you share here or send me the solution, please ?

**Comment by jordanA29** [comment]
@SatyabratKumarSingh    Can you  please share your solution? I have the same issue !

**Comment by isalo** [comment]
@SatyabratKumarSingh can you please send me your solution too? Thanks in advance.

**Comment by MannaRASSAA** [comment]
@SatyabratKumarSingh may you please share your solution? I have the same issue ! Thanks in advance.

**Comment by ghanashyam-c-k** [comment]
> 
> 
> yes.. I can send code if you need.

What was the solution?
