### ISSUE TITLE
newRowsAction not working as expected

### ISSUE THREAD

**Issue by spgodara** [ag-grid/ag-grid-angular#152]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report

```
**Current behavior**
I added newRowsAction = "keep" in filterParams for a column. The filter doesn't reset when I update rows using seRowData. But it resets when I call setRowData with blank array to clear all rows.
This issue is for set filter.

**Expected behavior**
The filter should be retained even if rows are cleared.

**Minimal reproduction of the problem with instructions**
Just set newRowsAction in filterParams for a column, apply filter to column and the clear rows using setRowData([])

**Please tell us about your environment:**
Angular 4, Windows 7

* **ag-grid-angular version:** 9.1.0

* **ag-Grid/ag-Grid-Enterprise version:** 9.1.0

* **Angular version:** 4

* **Browser:** Chrome 58

* **Language:** TypeScript 2.2.2

**Comment by seanlandsman** [comment]
Hi,

Can you please follow up on our Members Forum here https://ag-grid.com/forum/forumdisplay.php?fid=5

I have a few questions around this and I think the members forum might be a better place for it.

thanks
