### ISSUE TITLE
Can we customize the column menu

### ISSUE THREAD

**Issue by kkjallepalli** [ag-grid/ag-grid-angular#167]
Hi, I need a small doubt regarding the customizing the column menu. I am using ag-grid-angular with free version. Shall we override the column menu?

Below is the sample column over-riding example.

![image](https://user-images.githubusercontent.com/23303571/28790452-b5cee9b4-7646-11e7-9e1b-29eeacf5c915.png)

**Comment by seanlandsman** [comment]
As per the issue template, please dont raise support requests here

Either use stackoverflow, or our members forum https://ag-grid.com/forum/forumdisplay.php?fid=5
