### ISSUE TITLE
In-correct row index for master grid in master-detail usage

### ISSUE THREAD

**Issue by majoshi1** [ag-grid/ag-grid-angular#168]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This is for master-detail usage as in "Master Detail Example" from:
https://github.com/ag-grid/ag-grid-angular-example

**Expected behavior**
The master row index should be 0.

**Minimal reproduction of the problem with instructions**
Modify the sample to obtain selected row index for master.
let nodes = gridOptions.api.getSelectedNodes();
let selectedNode = nodes[0];
console.log(selectedNode.rowIndex);
Steps:
Expand first node in master grid.
Try to get selected row index for master.
It is 0, as expected.

Now select any row in detail grid.
And try to get selected row index for master.
It is 1, instead of 0.

**What is the motivation / use case for changing the behavior?**
In-correct behavior.

**Please tell us about your environment:**
Any environment.

* **ag-grid-angular version:** 2.0.X
9.1.0

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
ag-Grid

* **Angular version:** 2.0.X
Not checked.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2.2

**Comment by majoshi1** [comment]
Angular 4.x

**Comment by seanlandsman** [comment]
Hi

rowIndex is not the index of the row in which it appears in the grid, it is the index of the row as tracked by within the grid and subject to change as grid events occur

Why is it a problem that it changes - what are you trying to do with the rowIndex once you have it?

**Comment by seanlandsman** [comment]
Closed due to inactivity

**Comment by nagasainatht** [comment]
I am currently working on displaying the background color for the rows based on the condition.
Background color is working as expected.But once I selected and unselected the row because of not coming rowIndex as consistent all times I am not able to display required background color and hiding background color after unselection.

I am using react version of Ag-Grid enterprise version and it is 7.x

**Comment by nagasainatht** [comment]
Please suggest what should I prefer instead of rowIndex and I am using getRowStyle to write the required logic
