### ISSUE TITLE
Custom Floating Filter ag-grid Angular2

### ISSUE THREAD

**Issue by Jamunadevi-Vijayan** [ag-grid/ag-grid-angular#169]
**I'm submitting a Issue

**Current behavior**
Creating a IFilterAngularComp, with the option [floatingFilter]="true"

**Minimal reproduction of the problem with instructions**
_I am using https://embed.plnkr.co/ePKaio/.
And added property to grid [floatingFilter]="true".
When i search for a alphabet in filter, filtering is happening, but in the input floating filter, undefined is coming._

![image](https://user-images.githubusercontent.com/28444055/29631645-52bfccce-880e-11e7-98f6-c2e0be976447.png)

**Expected behavior**
In the input the value of the filter to be set

**What is the motivation / use case for changing the behavior?**
Creating a custom floating filter for a single column in a ag-grid in angular2 sample

**Please tell us about your environment:**
Operating system: Windows 7
IDE: Sublime
 package manager: NPM 

* **ag-grid-angular version:** 2.0.X
"ag-grid": "^9.1.0",
 "ag-grid-angular": "^9.1.0",

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
Yes

* **Angular version:** 2.0.X
Angular 2.4.10

TS: 2.0.10

**Comment by seanlandsman** [comment]
I'm afraid your plunker doesn't illustrate the problem you're having - there are no floating filters

When using floating filter components, you need to do more than simply enable them - you need to ensure all expected methods etc are present - please see https://www.ag-grid.com/javascript-grid-floating-filter-component/ for more information

**Comment by Jamunadevi-Vijayan** [comment]
Hi,
The plunker is not having my changes.
Please find the below attached code.

[sampleCustomFilter.zip](https://github.com/ag-grid/ag-grid-angular/files/1248129/sampleCustomFilter.zip)

**Comment by Jamunadevi-Vijayan** [comment]
can anyone help me on this
