### ISSUE TITLE
Aligned Grids not working.

### ISSUE THREAD

**Issue by sparrowonfire** [ag-grid/ag-grid-angular#170]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Grids don't sync together when aligned.

**Expected behavior**

Grids should work as designed

**Minimal reproduction of the problem with instructions**

I have the following code:
```
this.gridOptionsUpper = <GridOptions>{
      enableFilter: true,
      enableSorting: true,
      enableColResize: true,
      defaultColDef: {
        menuTabs: ['filterMenuTab',
                   'generalMenuTab',
                   'columnsMenuTab']
      },
      suppressHorizontalScroll: true,
      alignedGrids: []
    };
    this.gridOptionsLower = <GridOptions>{
      enableFilter: true,
      enableSorting: true,
      enableColResize: true,
      defaultColDef: {
        menuTabs: ['filterMenuTab',
                   'generalMenuTab',
                   'columnsMenuTab']
      },
      rowClass: 'bold-row',
      headerHeight: 0,
      alignedGrids: []
    };
   this.gridOptionsUpper.columnDefs = this.columnDefs;
    this.gridOptionsLower.columnDefs = this.columnDefs;
    this.gridOptionsUpper.alignedGrids.push(this.gridOptionsLower);
    this.gridOptionsLower.alignedGrids.push(this.gridOptionsUpper);
```

After following the guide [here](https://www.ag-grid.com/javascript-grid-aligned-grids/#aligned-grid-as-footer) I expected it to work however it does not seem to link the grids.

* **ag-grid-angular version:** 11.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 11.0.0

* **Angular version:** 4.3.2

* **Browser:** [Chrome XX]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi

Please take a look at this new example here: https://github.com/ag-grid/ag-grid-angular-example/tree/latest/systemjs_aot/app/aligned-grid-example
