### ISSUE TITLE
Resizing and re-ordering in ag-grid is not working on IPAD in angular 2

### ISSUE THREAD

**Issue by kkjallepalli** [ag-grid/ag-grid-angular#171]
Is ag-grid supports ipad ?

Grid is loading in all browsers , even in ipad also loading perfectly, But the resizing and reordering is not working? Is there any api for support ipad?

**Comment by seanlandsman** [comment]
ag-grid should work fine on an ipad - please see ag-grid.com for information

**Comment by charlesr1971** [comment]
No, ag-grid does NOT work on the iPad running iOS9, and I cannot update the OS, because I have an iPad 4...
