### ISSUE TITLE
ERROR TypeError: Unable to get property 'addEventListener' of undefined or null reference

### ISSUE THREAD

**Issue by cirekixog** [ag-grid/ag-grid-angular#172]
IE 10
ERROR TypeError: Unable to get property 'addEventListener' of undefined or null reference

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
