### ISSUE TITLE
ag-grid 13 angularCompileRows not working

### ISSUE THREAD

**Issue by jfuehner** [ag-grid/ag-grid-angular#173]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using the latest ag-grid v13 with the angularCompiledRows grid option property set to true none of my cellRenderer functions are rendering the angular directives.

**Expected behavior**
The grid worked without issue with the previous version of ag-grid v12.0.2

* **Angular version:** 2.0.X
AngularJS v1.6.5

**Comment by seanlandsman** [comment]
Hi

This has now been fixed - please try 13.0.1

thanks
