### ISSUE TITLE
IE 10 throw unable to get property 'addEventListener' of undefined or null reference

### ISSUE THREAD

**Issue by cirekixog** [ag-grid/ag-grid-angular#174]
**I'm submitting a ...**
```
bug report
```

**Unable to get property 'addEventListener' of undefined or null reference**

* **ag-grid-angular version:** 12.0.0

* **Angular version:** 4.3.6

* **Browser:** [ IE 10 ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

[Screenshot](https://ibb.co/nqj4XQ)

![Screenshot](https://image.ibb.co/fGDysQ/Sketch.png)

**Comment by seanlandsman** [comment]
Hi

Thanks for the report, but I'm afraid I dont have enough to go on here.

If you provide the steps your follow, or a repo we can take a look at we'll be happy to investigae furhter
