### ISSUE TITLE
Angular equivalent of plain JS

### ISSUE THREAD

**Issue by rakeshsagar29** [ag-grid/ag-grid-angular#175]
Hi, 
Please let me know the angular equivalent of below code : 

document.addEventListener("DOMContentLoaded", function() {

    // lookup the container we want the Grid to use
    var eGridDiv = document.querySelector('#myGrid');

    // create the grid passing in the div to use together with the columns & data we want to use
    new agGrid.Grid(eGridDiv, gridOptions);
});

I am not sure how to get the reference of "agGrid" in angular. 
I have some code written in plain JS. I have to convert the same in Angular2. agGrid is being instantiated in plain JS and being used everywhere.(I can't share the whole code here.). I have to get the reference on the same for the whole of component constructor.

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
