### ISSUE TITLE
Excessive Change Detection in Angular 2

### ISSUE THREAD

**Issue by AlDrag** [ag-grid/ag-grid-angular#176]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Clicking/Hovering rows triggers change detection multiple times.

**Expected behavior**
Since AG-GRID is native JS, it shouldn't be triggering any change detection.

**Minimal reproduction of the problem with instructions**
To reproduce this, put a DoCheck in your ag-grid-angular wrapper and log the checks, as shown in this plunker.
https://plnkr.co/edit/Lw1764fbKfMqjyACQm6L?p=info

**What is the motivation / use case for changing the behavior?**
Reducing Change Detection should greatly increase performance of large applications using AgGrid.

**Please tell us about your environment:**
OSX Sierra 10.12.6
Chrome 60.0.3112.113
Intellij Idea 2017.2.1

* **ag-grid-angular version:** 2.0.X
ag-grid-angular 13.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
ag-grid 13.0.2
ag-grid-enterprise 13.0.1

* **Angular version:** 2.0.X
angular 4.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.3.1

**Comment by seanlandsman** [comment]
Although the underlying grid is indeed in javascript, the wrapper we provide isn't - as such we do utilise change detection for a variety of reasons, but primarily when users provide custom angular components

**Comment by pantonis** [comment]
What does this mean? Was this behavior changed?

**Comment by alan-bio** [comment]
AG-Grid triggers Angular/ZoneJS's change detection on little things such as hovering rows in ag-grid. I personally feel it's excessive because if you for example run your mouse down 100 rows in ag-grid very quickly then you have just triggered 100 or more cycles of change detection.

Maybe I am wrong and this really is needed, but I feel change detection should be triggered only for things such as clicking etc, or not at all. But I can't confirm if I am correct as I need to look into it more myself.

**Comment by AlDrag** [comment]
AG-Grid triggers Angular/ZoneJS's change detection on little things such as hovering rows in ag-grid. I personally feel it's excessive because if you for example run your mouse down 100 rows in ag-grid very quickly then you have just triggered 100 or more cycles of change detection.

Maybe I am wrong and this really is needed, but I feel change detection should be triggered only for things such as clicking etc, or not at all. But I can't confirm if I am correct as I need to look into it more myself.

**Comment by pantonis** [comment]
Insaw rhis behavior with some other control which was using Hostlistener and on mouse move it was triggering change detection.  This can lead to poor performance.

**Comment by AlDrag** [comment]
That kind of thing should probably be ran outside of the Angular zone.
@seanlandsman has a very good point about how custom ag-grid angular components rely on change detection however.

**Comment by klinki** [comment]
I feel the same as @ArekSliwa . We have very large application with very costly time detection cycles. Ag-grid triggers change detection on hover, so the application lags every time user moves mouse on the grid. Which is very often. And the performance is really bad especially in IE11...

I know we should solve that in our app, but I think ag-grid should not trigger too much change detection.

**Comment by seanlandsman** [comment]
Release 21 should remove the vast majority of this - I suggest you upgrade and retry with ver 21 of ag-grid

**Comment by klinki** [comment]
Thanks, version 21 seems really much better.
