### ISSUE TITLE
Unexpected token < error when loading the library

### ISSUE THREAD

**Issue by smulanry** [ag-grid/ag-grid-angular#177]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I am trying to run the application, I am getting the following error, in the chrome console, and the application never renders.
```
zone.js:654 Unhandled Promise rejection: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:4800/node_modules/ag-grid-angular/dist/ng2FrameworkComponentWrapper.js:15:17)
	    at eval (http://localhost:4800/node_modules/ag-grid-angular/dist/ng2FrameworkComponentWrapper.js:100:4)
	    at eval (http://localhost:4800/node_modules/ag-grid-angular/dist/ng2FrameworkComponentWrapper.js:101:3)
	Evaluating http://localhost:4800/node_modules/ag-grid
	Evaluating http://localhost:4800/node_modules/ag-grid-angular/dist/ng2FrameworkComponentWrapper.js
	Evaluating http://localhost:4800/node_modules/ag-grid-angular/dist/agGridNg2.js
	Evaluating http://localhost:4800/node_modules/ag-grid-angular/dist/aggrid.module.js
	Evaluating http://localhost:4800/node_modules/ag-grid-angular/main.js
	Evaluating http://localhost:4800/core/app.js
```

I believe the issue is being caused by `line 3` of `ng2FrameworkComponentWrapper.ts`.  

I am not sure you are doing 
```import {FrameworkComponentWrapper, BaseComponentWrapper, WrapableInterface}  from 'ag-grid';```  
instead of 
```import {FrameworkComponentWrapper, BaseComponentWrapper, WrapableInterface}  from 'ag-grid/main';```

My web server is making a request for the `ag-grid` node module and returning 404 html markup instead of javascript, I manually modifed the the compiled file in the dist folder and it worked as soon as I changed that import to be 'ag-grid/main'

**Expected behavior**

Application should work.  

* **ag-grid-angular version:** 13.3.1

* **ag-Grid/ag-Grid-Enterprise version:** N/A

* **Angular version:** 4.3.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [TypeScript X.X]

**Comment by seanlandsman** [comment]
Hi 

I'm afraid I'm unable to reproduce this - 'ag-grid' should exist and should just point to the main file according to the package.json.

If you can share you setup perhaps we can take a look?
