### ISSUE TITLE
Error: Property 'onReady' is private and only accessible within class 'RichGridComponent'.

### ISSUE THREAD

**Issue by tamtakoe** [ag-grid/ag-grid-angular#178]
There is incorrect code in example and plnker on the page: https://www.ag-grid.com/best-angular-2-data-grid/?framework=angular#gsc.tab=0

If you use options in the angular template they have to be public.
Make  `gridReady`, `gridOptions`, `columnDefs`, `rowData`, `icons` in the RichGridComponent and `value`, `styles` in the ProficiencyCellRenderer as public or don't use it in the template. It doesn't work with AOT compilation.

**Comment by seanlandsman** [comment]
Fixed - will be in the next release

thanks
