### ISSUE TITLE
cellRendererFramework with api.updateRowData

### ISSUE THREAD

**Issue by jbarber2016** [ag-grid/ag-grid-angular#180]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I set cellRendererFramework and also call updateRowData({update: updates}); the refresh function in the cellRenderer is never called.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-angular version:** 2.0.X

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

ag-Grid version: 13.2
* **Angular version:** 2.0.X

Angular version: 4.4.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
As per the issue template please provide a reproducible example - we can then investigate and assist

thanks
