### ISSUE TITLE
Custom Column Menu Not able to call Custom Function

### ISSUE THREAD

**Issue by srikant21** [ag-grid/ag-grid-angular#181]
**Current behavior**
I have created the custom column menu by using "getMainMenuItems" and i want to call custom function when i click the the column menu.But when i clicked the column menu it is showing the error custom function is not allowed.
Please find the plunker below
https://plnkr.co/edit/BgrbaeO48NvDzXTOoTr9?p=preview 

**Expected behavior**
Custom column menu should call the custom function which i used. 

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

Windows 7,Visual Studio Code,

* **ag-grid-angular version:** 2.0.X
ag-grid version-13.0.x

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
ag-grid trail version

* **Angular version:** 2.0.X
Angular 2 & Angular 4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Yes

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript:-2.2.x

**Comment by seanlandsman** [comment]
You need to bind to "this" for this to work. You also need to user an arrow function (or equivalent mechanism) in the switch 

https://plnkr.co/edit/6LVFtFehAPh4mIS3yHzk?p=preview

thanks
