### ISSUE TITLE
"Module not found" error with Angular 5 and Webpack

### ISSUE THREAD

**Issue by theodorejb** [ag-grid/ag-grid-angular#182]
**I'm submitting a**
```
[x] bug report
```

**Current behavior**
When I run Webpack after compiling my app with Angular 5.0.0-rc.6, I get the following errors:
* ERROR in ./compiled_ts/node_modules/ag-grid-angular/dist/agGridNg2.ngfactory.js Module not found: Error: Can't resolve './agGridNg2'
* ERROR in ./compiled_ts/node_modules/ag-grid-angular/dist/agGridNg2.ngfactory.js Module not found: Error: Can't resolve './baseComponentFactory'
* ERROR in ./compiled_ts/node_modules/ag-grid-angular/dist/agGridNg2.ngfactory.js Module not found: Error: Can't resolve './ng2FrameworkComponentWrapper'
* ERROR in ./compiled_ts/node_modules/ag-grid-angular/dist/agGridNg2.ngfactory.js Module not found: Error: Can't resolve './ng2FrameworkFactory'

**Expected behavior**
ag-Grid should be compiled and bundled correctly with Angular 5.

**Minimal reproduction of the problem with instructions**
I'm running `ngc` with the following tsconfig.json file:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "outDir": "compiled_ts",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true
  },
  "files": [
    "app/app.module.ts",
    "app/main.ts"
  ],
  "angularCompilerOptions": {
    "preserveWhitespaces": false,
    "skipMetadataEmit" : true
  }
}
```

My main.ts file looks like this:

```typescript
import {enableProdMode} from '@angular/core';
import {platformBrowser} from '@angular/platform-browser';
import {AppModuleNgFactory} from './app.module.ngfactory';

enableProdMode();
platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```

`ngc` appears to run without errors, but the files it puts in the compiled_ts folder for ag-Grid are apparently incorrect, since when Webpack runs I get the above errors. Note that Angular 5.0.0-rc.6 + Webpack works fine for me in an app without ag-Grid.

**What is the motivation / use case for changing the behavior?**
Angular 5 final will be released any day now, and ag-Grid should support it.

**Please tell us about your environment:**
Windows 8.1, Node 8.8.

* **ag-grid-angular version:** 13.3.0
* **ag-grid version:** 13.3.1
* **Angular version:** 5.0.0-rc.6

* **Browser:** all

* **Language:** TypeScript 2.4.2

**Comment by seanlandsman** [comment]
I tested rc4 two days ago and it was fine - I'll test rc6 and see how it goes

thanks

**Comment by seanlandsman** [comment]
This has already been taken account as part of the previous rc testing. When angular 5 is released we'll release a minor version to support it.

thanks

**Comment by theodorejb** [comment]
Angular 5 was released yesterday: https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced.

**Comment by theodorejb** [comment]
@seanlandsman I'm still getting this exact same error with Angular 5.0.1 and ag-grid 14.1.

**Comment by seanlandsman** [comment]
@theodorejb if you can provide an repro of this I'd be happy to take a look. In the meantime though https://github.com/ceolter/ag-grid-angular-example/ repo has both webpack and webpack 2 examples using Angular 5 - perhaps you can take a look at them for reference?

**Comment by theodorejb** [comment]
Thanks @seanlandsman. I have looked at that example, but it doesn't seem to be using AOT compilation. Do you have a working example that uses AOT compilation with Webpack 3?

**Comment by seanlandsman** [comment]
Hi,

No, not with Webpack 3. The Angular CLI example uses AOT though if that helps (probably not)

An example with webpack 3 is on my list, but I dont have anything ready for that yet I'm afraid

**Comment by theodorejb** [comment]
I was able to work around this issue by importing `AgGridModule` from src instead of main:

```typescript
import {AgGridModule} from 'ag-grid-angular/src/aggrid.module';
```

However, for this to work I had to set the `noImplicitAny` TypeScript option to `false`, otherwise I got the following error:

> node_modules/ag-grid-angular/src/ng2FrameworkComponentWrapper.ts(44,17): error TS7017: Element implicitly has an 'any' type because type 'DynamicAgNg2Component' has no index signature.

**Comment by seanlandsman** [comment]
@theodorejb if you can provide an example of your setup I should be able to improve on  what you have, or at least make improvements our side so that it works as expected for you

thanks

**Comment by theodorejb** [comment]
Apparently the same sort of error occurs if you try to use Angular 5 with the SystemJS AOT example in the ag-grid-angular-example repo. I made a fork that demonstrates this: https://github.com/theodorejb/ag-grid-angular-example/tree/aot-error.

When running `npm run clean-build:aot`, I get the following error as part of the aot-bundle step:

```
Error on fetch for aot/node_modules/ag-grid-angular/dist/ng2FrameworkFactory.js at file:///C:/Users/theodorebr/Documents/GitHub/ag-grid-angular-example/systemjs_aot/aot/node_modules/ag-grid-angular/dist/ng2FrameworkFactory.js
    Loading aot/node_modules/ag-grid-angular/dist/agGridNg2.ngfactory.js
    Loading aot/app/rich-grid-example/rich-grid.component.ngfactory.js
    Loading aot/app/app.module.ngfactory.js
    Loading aot/app/boot-aot.js
    Error: ENOENT: no such file or directory, open 'C:\Users\theodorebr\Documents\GitHub\ag-grid-angular-example\systemjs_aot\aot\node_modules\ag-grid-angular\dist\ng2FrameworkFactory.js'
```

**Comment by theodorejb** [comment]
This issue still occurs with Angular 5.0.5. Try using Angular 5 with the official ag-Grid AOT example and you should be able to reproduce it.

**Comment by theodorejb** [comment]
This is still broken in the latest version of ag-Grid, and my workaround doesn't seem to work anymore with Angular 5.2. @seanlandsman do you have any working example of using ag-Grid with Angular 5.x AOT compilation? The official [SystemJS AOT example](https://github.com/ag-grid/ag-grid-angular-example/tree/master/systemjs_aot) is still using Angular 4, and didn't work with Angular 5 when I tested it.

**Comment by theodorejb** [comment]
Update: I was finally able to get it working by removing the `outDir` compiler option in my tsconfig.json file. I think this issue is caused by angular/angular#20006.
