### ISSUE TITLE
Angular v5.X - stack error with ng build --prod

### ISSUE THREAD

**Issue by Greg5ki** [ag-grid/ag-grid-angular#184]
Works OK with ag-grid v13.0.0 but not 14.X

**I'm submitting a ...**
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This is on a fresh install of Angular CLI 1.5 and a new app.

When compiling in Angular-CLI 1.5 against Angular 5.0.0 I get the following error:

`ERROR in ./node_modules/ag-grid/dist/lib/gridOptionsWrapper.js
Module build failed: RangeError: Maximum call stack size exceeded
    at Object.forEachChild (C:\Code\v5\node_modules\typescript\lib\typescript.js:15973:26)
    at traverse (C:\Code\v5\node_modules\typescript\lib\typescript.js:32626:110)
    at visitNode (C:\Code\v5\node_modules\typescript\lib\typescript.js:15944:20)
    at Object.forEachChild (C:\Code\v5\node_modules\typescript\lib\typescript.js:16080:24)
    at traverse (C:\Code\v5\node_modules\typescript\lib\typescript.js:32626:110)
    at visitNode (C:\Code\v5\node_modules\typescript\lib\typescript.js:15944:20)
    at Object.forEachChild (C:\Code\v5\node_modules\typescript\lib\typescript.js:16013:21)
    at traverse (C:\Code\v5\node_modules\typescript\lib\typescript.js:32626:110)
    at visitEachNode (C:\Code\v5\node_modules\typescript\lib\typescript.js:15956:30)
    at Object.forEachChild (C:\Code\v5\node_modules\typescript\lib\typescript.js:16143:24)
    at traverse (C:\Code\v5\node_modules\typescript\lib\typescript.js:32626:110)
    at visitNode (C:\Code\v5\node_modules\typescript\lib\typescript.js:15944:20)
    at Object.forEachChild (C:\Code\v5\node_modules\typescript\lib\typescript.js:16141:21)
    at traverse (C:\Code\v5\node_modules\typescript\lib\typescript.js:32626:110)
    at visitEachNode (C:\Code\v5\node_modules\typescript\lib\typescript.js:15956:30)
    at Object.forEachChild (C:\Code\v5\node_modules\typescript\lib\typescript.js:16134:24)
 @ ./node_modules/ag-grid/dist/lib/gridSerializer.js 16:27-58
 @ ./node_modules/ag-grid/main.js
 @ ./node_modules/ag-grid-angular/dist/agGridNg2.js
 @ ./node_modules/ag-grid-angular/dist/aggrid.module.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts`

**Expected behavior**
Should compile OK.

**Minimal reproduction of the problem with instructions**
In Angular CLI:
run: ng new test
add reference to ag-grid
run: ng build --aot --prod

**Please tell us about your environment:**
Angular CLI: 1.5.0
Node: 6.9.5
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

angular/cli: 1.5.0
angular-devkit/build-optimizer: 0.0.32
angular-devkit/core: 0.0.20
angular-devkit/schematics: 0.0.35
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.8.0
schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1

* **ag-grid-angular version:** 14.0.X

* **Angular version:** 5.0.X

* **Browser:** all

* **Language:** TypeScript 2.4.2

**Comment by otionstem** [comment]
I am able to compile.  Grid, however, does not render correctly.

**Comment by Greg5ki** [comment]
Compiles OK with ag-grid v13.0.0 but not 14.X

**Comment by seanlandsman** [comment]
We'll be doing a release next week to support this. 

We've did a release yesterday which was a little too close to the Angular release for full testing.

**Comment by dzonatan** [comment]
@Greg5ki does it compiles with AOT for you?
Only JIT works for me..

**Comment by Greg5ki** [comment]
Nope.

**Comment by dark484** [comment]
Got the same error with Angular-CLI 1.5, but then got it working changing the run from "ng build --prod" to "ng build --prod --build-optimizer=false". In  [the documentation of Angular-CLI](https://github.com/angular/angular-cli/wiki/build#bundling--tree-shaking) is explained that build-optimizer is set to true with AOT and Angular 5. 

Maybe the build-optimizer tries to change or extract something from agGridNg2.js and when it fails, it causes this error.

**Comment by seanlandsman** [comment]
Hi

14.1.0 has been released and support Angular 5.

Note that the Angular CLI & Webpack examples have been updated to use Angular 5, but the ngTools and SystemJS examples still use Angular 4 (as we have users that will be using both for a while)

thanks

**Comment by dzonatan** [comment]
Very strange things happening here.
1 out of 10 build fails with AOT enabled. The same "gridOptionsWrapper.js Module build failed: RangeError: Maximum call stack size exceeded at Object.forEachChild" is thrown.

It happens on both my local machine and CI server. Don't know yet how to reproduce...

**Comment by dzonatan** [comment]
@seanlandsman please reopen this issue.

**Comment by seanlandsman** [comment]
Looks like this is related to this angular compiler issue https://github.com/angular/angular/issues/19979

I'll investigate but it may be that this is something that has to wait for the angular team

**Comment by seanlandsman** [comment]
This appears to be related to cyclic dependencies. The behaviour is also intermittent - sometimes it'll run successfully, sometimes not, which is odd.

Nevertheless, you can get this to work 100% of the time by adding something like this to your package.json:

    "prod": "node --stack_size=4048 node_modules/.bin/ng build --prod",

**Comment by seanlandsman** [comment]
Tracked by issue AG-1082 our side

**Comment by seanlandsman** [comment]
Issue is currently with the CLI team: https://github.com/angular/angular-cli/issues/5618#issuecomment-344320980

**Comment by seanlandsman** [comment]
Angular CLI 1.6.2 fixes this issue

**Comment by Arikael** [comment]
unfortunately angular-cli 1.6.2 does not fix the issue or the issue has been reintroduced.
we are using ag-grid 15, angular 5.2.0, cli 1.6.4 and typescript 2.5.3 and the error happens (again?)

**Comment by Arikael** [comment]
update.
Today it works without any issues.
Since I work in a virtualized environment which has performance issues from time to time I think this might have something to do with it.

**Comment by whiteblackkeys** [comment]
I though it was fixed but it happened again few days ago (ag-grid v16, angular/cli v1.6.5), I agree it could be related to some performance issues...

**Comment by jonbcard** [comment]
Can also confirm that this has never fully been resolved. Have continued to see if sporadically on our build server (virtualized and a little slower) but not locally. Running ag-grid v15 and angular-cli 1.6.3. @seanlandsman any more information on this from the ag-grid side?

**Comment by Dev-Force** [comment]
seems like i can reproduce it when building a project that relies on libsodium too. @seanlandsman 's answer solved the issue.

**Comment by hajderr** [comment]
Can confirm this occurs intermittently 
 "ag-grid": "^16.0.1",
 "ag-grid-angular": "^16.0.0",

**Comment by kasimkha** [comment]
Maximum call stack size exceeded in "@angular/cli": "^1.7.0"

**Comment by Greg5ki** [comment]
I upgraded to 1.7.0 and 16.0.0 and am not getting any of these issues.

**Comment by martor** [comment]
Same issue here:
```
ERROR in ./node_modules/ag-grid/dist/lib/gridOptionsWrapper.js
Module build failed: RangeError: Maximum call stack size exceeded
```

angular 2.5.2
angular-cli 1.7.0
ag-grid 16.0.0
ag-grid-angular 16.0.0
typescript: 2.6.2

Happens only on production build with 
`ng build --prod`

**Comment by hbthanki** [comment]
@martor I am also getting this issue with ag-grid. 
@seanlandsman @ceolter: Did you guys encountered this issue with enterprise too?

   "@angular/animations": "^5.2.6",
    "@angular/cdk": "^5.2.2",
    "@angular/common": "^5.2.6",
    "@angular/compiler": "^5.2.6",
    "@angular/compiler-cli": "^5.2.6",
    "@angular/core": "^5.2.6",
    "@angular/flex-layout": "^2.0.0-beta.12",
    "@angular/forms": "^5.2.6",
    "@angular/http": "^5.2.6",
    "@angular/material": "^5.2.2",
    "@angular/platform-browser": "^5.2.6",
    "@angular/platform-browser-dynamic": "^5.2.6",
    "@angular/platform-server": "^5.2.6",
    "@angular/router": "^5.2.6",
    "ag-grid": "14.2.0",
    "ag-grid-angular": "14.2.0",
    "ag-grid-enterprise": "14.2.0"
    "@angular/cli": "^1.7.1",
    "typescript": "^2.7.2"

   Happens with --aot --build-optimizer

**Comment by anashusain** [comment]
Hello guys, i had same issues, this issue is because of conflict of angular library js files with the jsp or html scripts where you might have merged ur angular code.... please check if there are some prototype methods  which will be overwriting  angular core files...

**Comment by enniob** [comment]
I get the same error when I build using `ng build --prod` but if I do `ng build --prod --build-optimizer=false` it works fine. 

I'm using the the following:

"@angular/cli": "^1.7.3"
"ag-grid": "^17.0.0",
"ag-grid-angular": "^17.0.0",
"@angular/core": "5.2.8",

**Comment by Thommas** [comment]
Thank you for the quick fix.

`--build-optimizer=false`.

**Comment by chfw** [comment]
I had the same problem but after I upgrade cli from 1.6.8 to 1.7.2, the problem is gone

Here is my versions:

```
    "ag-grid": "^16.0.1",
    "ag-grid-angular": "^16.0.0",
    "@angular/cli": "1.7.2",
```

**Comment by PeymanGhadiri** [comment]
Same error here : 
`ERROR in ./node_modules/ag-grid/dist/lib/gridOptionsWrapper.js
Module build failed: RangeError: Maximum call stack size exceeded
`
packages:
```
"@angular/compiler-cli": "^5.2.0",
"@angular/common": "^5.2.0",
"@angular/compiler": "^5.2.0",
"@angular/core": "^5.2.0",

"@angular/cli": "~1.7.4",

"ag-grid": "^17.1.1",
"ag-grid-angular": "^17.1.0",
"ag-grid-enterprise": "^17.1.1",
```

**Comment by phyratokar** [comment]
Same error also in Angular 6.0.1:
`
ERROR in ./node_modules/ag-grid/dist/lib/gridOptionsWrapper.js Module build failed: RangeError: Maximum call stack size exceeded
at containsArgumentsReference
`
package.json:
`
    "@angular/cdk": "^6.0.1",
    "@angular/common": "6.0.1",
    "@angular/compiler": "6.0.1",
    "@angular/core": "6.0.1",
    "@angular/material": "^6.0.1",
    "ag-grid": "^17.1.1",
    "ag-grid-angular": "^17.1.0",
    "ag-grid-enterprise": "^17.1.1",
    "rxjs": "^6.1.0",
`

**Comment by im85288** [comment]
Also running into this issue, not yet migrated to version 6

` "@angular/cdk": "^5.0.0-rc.1",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.2.5",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",`

**Comment by dzonatan** [comment]
Tried to use uncompiled version of `ag-grid` directly in project and got a lot of "Circular dependency detected" warnings (~100) in development mode which might be the case why "Maximum call stack size" error is reached.

```
...

WARNING in Circular dependency detected:
src\ag-grid\src\ts\alignedGridsService.ts -> src\ag-grid\src\ts\gridOptionsWrapper.ts -> src\ag-grid\src\ts\gridApi.ts -> src\ag-grid\src\ts\csvCreator.ts -> src\ag-grid\src\ts\gridSerializer.ts -> src\ag-grid\src\ts\columnController\columnController.ts -> src\ag-grid\src\ts\rendering\autoWidthCalculator.ts -> src\ag-grid\src\ts\rendering\rowRenderer.ts -> src\ag-grid\src\ts\gridPanel\gridPanel.ts -> src\ag-grid\src\ts\alignedGridsService.ts

WARNING in Circular dependency detected:
src\ag-grid\src\ts\columnController\columnApi.ts -> src\ag-grid\src\ts\columnController\columnController.ts -> src\ag-grid\src\ts\entities\columnGroup.ts -> src\ag-grid\src\ts\entities\column.ts -> src\ag-grid\src\ts\eventService.ts -> src\ag-grid\src\ts\logger.ts -> src\ag-grid\src\ts\gridOptionsWrapper.ts -> src\ag-grid\src\ts\gridApi.ts -> src\ag-grid\src\ts\csvCreator.ts -> src\ag-grid\src\ts\gridSerializer.ts -> src\ag-grid\src\ts\selectionController.ts -> src\ag-grid\src\ts\columnController\columnApi.ts

.....
```

**Comment by rayzrchen** [comment]
I had the similar problem. My walk around solution is not to import "GridApi" or "ColumnApi" from "ag-grid"

**Comment by dzonatan** [comment]
@rayzrchen With angular v6 it's enough to import `AgGridModule` (which is mandatory to run ag-grid) to get this `Maximum call stack size exceeded` in production build.

**Comment by Ahmad-Magdy** [comment]
+1 after upgrading to Angular 6

**Comment by rayzrchen** [comment]
`import {AgGridModule} from 'ag-grid-angular';`
this link of code will not cause any build error

**Comment by rayzrchen** [comment]
@dzonatan But import ColumnApi or GridApi will cause the build error:
`import {ColumnApi, GridApi} from 'ag-grid';`
I am also using the Angular 6. I have tested it.

**Comment by Teamop** [comment]
Got same error with angular-cli 6.0.3 with ag-grid 17.1.1 and ag-grid-angular 17.1.0
@seanlandsman should we reopen this issue or create a new one for Angular 6 as there's a lot of feedback here?

**Comment by dzonatan** [comment]
@rayzrchen Interesting. For me it's enough to import just `AgGridModule` and register in my root module to start getting this error..

**Comment by kritisoft** [comment]
Any Solution for this Issue ??

**Comment by im85288** [comment]
The only workaround is what has been said in many of the comments above. Use -build-optimizer=false

Not sure if the developers are looking at this as there has been no comment for quite some time and the issue is strangely marked as closed. Perhaps worth creating a new issue to bring it back to their attention as the "workaround" is not something I can go to PROD with and would mean having to use a different component than Ag Grid

**Comment by dzonatan** [comment]
I [did some investigation](https://github.com/angular/angular-cli/issues/9636#issuecomment-390203543) and found out that it might be not entirely `ag-grid` problem.

**Comment by Teamop** [comment]
I don't know the exactly reason, but today when I removed the `package-lock.json` and installed again, I can run `ng build --prod` without this issue.

**Comment by ImranAhmed** [comment]
I am seeing this, too.

Set-up as follows.

 "@angular/core": "6.0.0",
"@angular/cli": "^6.0.3",
"ag-grid": "17.1.1",
"ag-grid-angular": "17.1.0",

OK:
`ng build -- --prod --build-optimizer=false`

Fails with error:
`run ng build -- --prod`

```
ERROR in ./node_modules/ag-grid/dist/lib/gridOptionsWrapper.js
Module build failed: RangeError: Maximum call stack size exceeded
    at traverse (F:\dev\qbridge\qb-web-admin\node_modules\typescript\lib\typescript.js:30483:30)
```

**Comment by kritisoft** [comment]
removed the package-lock.json and installed again, I can run ng build --prod without this issue.
@Teamop  this helped

**Comment by ImranAhmed** [comment]
I tried to delete package-lock.json. I also deleted node_modules but still get the issue.

**Comment by jaganlal** [comment]
+1

"@angular/cli": "6.0.1",
"@angular/core": "6.0.1",
"ag-grid": "^17.1.1",
"ag-grid-angular": "^17.1.0"

**Comment by pnag90** [comment]
+1
    "@angular/core": "5.2.7",
    "@angular/cli": "1.6.8",
    "@angular/compiler-cli": "5.2.7",
    "ag-grid": "^17.1.1",
    "ag-grid-angular": "^17.1.0",
    "typescript": "2.6.2",

**Comment by raghunayudurayapudi** [comment]
it is a random error even though you update the versions or bump the versions back and forth  no use .Try to run the build again it will work

**Comment by alisalama** [comment]
This fix worked for me...
1. Removed all references to ColumnApi, GridApi and ColDef.
2. Updated these references
`npm install @angular-devkit/core --save
npm install @angular-devkit/build-optimizer --save
npm install @angular-devkit/build-angular --save`

**Comment by narunbabu** [comment]
Just modify budgets in angular.json file. You need to specify value for baseline with the maximum budget you are getting. https://medium.com/frontend-coach/setting-budgets-with-new-angular-cli-e6974e85777f

**Comment by vlodko** [comment]
Still having this issue time to time on the build server :(
