### ISSUE TITLE
Mouse Events triggering application wide change detection

### ISSUE THREAD

**Issue by instantaphex** [ag-grid/ag-grid-angular#185]
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question

**Current behavior**
When mousing over cells and rows, the mouse events are triggering change detection which is absolutely killing my applications performance in IE11

**Expected behavior**
Mouse events should not trigger change detection

**Minimal reproduction of the problem with instructions**
I've included a minimal plunker which reproduces the problem.
https://plnkr.co/edit/1kYVxw?p=preview

**What is the motivation / use case for changing the behavior?**
IE11 performance is horrible in my application.  The ag-grid demo application performs perfectly, but ag-grid-angular does not

**Please tell us about your environment:**
IE11

* **ag-grid-angular version:** 2.0.X
13.3.0

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
13.3.1

* **Angular version:** 2.0.X
4.2.0

* **Browser:** All browsers, but performance takes a serious dive in IE11 in larger applications

* **Language:** all

**Comment by instantaphex** [comment]
The more I look into this the more I wonder if this isn't more of an issue for ag-grid as opposed to ag-grid-angular.  in order to accommodate this, I wonder if BaseFrameworkFactory would need to be changed to add support for addEventListener with runOutsideAngular

**Comment by eivindr** [comment]
A similar problem existed in the froala wrapper. Not sure if it will help but the froala fix is mentioned here: https://github.com/froala/angular-froala-wysiwyg/issues/67#issuecomment-334886886

**Comment by instantaphex** [comment]
@eivindr It looks like a fix like that would cause ALL events to run outside of angular which is probably not what we would want.  With zone.js monkey patching all events, mouseover, mouseout, mousemove, mouseenter, mouseleave, and scroll trigger change detection in angular.  These listeners and callbacks are being set in ag-grid itself, not the wrapper.

I've been able to find a two-fold workaround but it's very hacky and it would be much better if ag-grid addressed the issue directly.

**Comment by makinggoodsoftware** [comment]
This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months.

As a result, we don’t have capacity to take feature requests from GitHub.e

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by MrCelestis** [comment]
Since the issue looks too difficult to be fixed properly, maybe we could at least have "suppressXXX" grid options to disable such events at all? Like, for those who don't need features like "hover css class on cells"... This behavior is terrific for large applications.

**Comment by stasberkov** [comment]
Fully agree with @MrCelestis . We are trying to use ag-grid because we need performant enough grid. Extra change detections on mouse hover kill performance.

**Comment by instantaphex** [comment]
If anyone is looking for a quick and dirty fix, see my comments on the ag-grid issue list.

[https://github.com/ag-grid/ag-grid/issues/2034](url)

I'm currently running ag-grid 14.0.0.  Due to the nature of the monkey patching solution I've used, it may not work with future version unfortunately.  For my project it gave us a pretty good performance increase.

**Comment by ArekSliwa** [comment]
this link doesn't work. Also fix is needed, it's not some minor bug.

**Comment by jdp80** [comment]
Mouseover forces repeated change detection across the whole application, this can't be the way things are supposed to work? In a complex app this is really killing us. Chrome does it quickly, at least, but still with 100% CPU spikes and framerate drops - IE11 barely runs. What can we do to improve performance?

**Comment by giniedp** [comment]
Our team faced the same issue. Luckily we have a custom ag-grid-angular binding which we can control. We changed it so ag-grid runs completely outside of the angular zone, but custom event listeners are still sent back to the angular zone.

I sketched an example on stackblitz
https://stackblitz.com/edit/issue-ag-grid-change-detection

This is with ag-grid Version 19. Implementation feels hacky, since some places have to be monkeypatched. If there is interest, i can improve the implementation and port it to recent ag-grid version.

**Comment by seanlandsman** [comment]
This issue has now been fixed. Please upgrade to at least version 22.

**Comment by giniedp** [comment]
it still triggers change detection when scrolling through the grid.

**Comment by giniedp** [comment]
@seanlandsman i have updated the example.
https://stackblitz.com/edit/issue-ag-grid-change-detection

You clearly see the difference between the ag-grid-angular implementation and the custom angular binding. The custom implementation triggers no change detection turns during grid interactions (sort, filter, scroll, click)
