### ISSUE TITLE
onGridReady never firing?

### ISSUE THREAD

**Issue by damonus-prime** [ag-grid/ag-grid-angular#187]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using ag-grid-angular in what seems to be a completely standard way.  Data load is being done from a service, which should be called in the onGridReady function.  onGridReady event is never firing.

**Expected behavior**
onGridReady event fires.

relevant code excerpts:
package.json:

`"@angular/core": "4.2.6",
    "ag-grid": "^13.3.1",
    "ag-grid-angular": "^13.3.0",`

markup:

`<ag-grid-angular #agGrid
                [gridOptions]="gridOptions"
                id="currencyGrid"
                style="height: 500px; width: 100%;"
                class="ag-semantic">
            </ag-grid-angular>`

typescript:

`this.gridOptions = {
            columnDefs: this.columnDefs,
            rowHeight: 40,
            headerHeight: 40,
            onGridReady: () => {
                console.log('grid ready');
                this.loadAll();
            }
        };`

Other info:  All this because I am trying to use a Component as a CellRenderer.

onGridReady DOES fire if I uncomment the following code, which appears just below the typescript block above:

`// const gridElement: HTMLElement = <HTMLElement>document.querySelector('#currencyGrid');
        // // console.log(gridElement);
        // this.grid = new Grid(gridElement, this.gridOptions);`

Problem is, if I do that and try to specify a CellRendererFramework in a columnDef, I get this error:

"You are specifying a framework component but you are not using a framework version of ag-grid for : cellRenderer" . 

which seems odd, since I assume ag-grid-angular IS a framework version of ag-grid.

At any rate.  Advice/Guidance would be appreciated.

**Comment by seanlandsman** [comment]
From the looks of this you're mixing two types of grid support - plain JS and angular.

As you want to use angular you never need to do something like new Grid yourself - I suggest you take a look at the angular docs here: https://www.ag-grid.com/best-angular-2-data-grid/ for guidance on how to configure and use ag-grid with angular

thanks

**Comment by damonus-prime** [comment]
Actually I'm not.  The lines calling new Grid are commented out like I said.  I also said that onGridReady only fires IF I uncomment those lines.  I get no errors of any kind in the console.  

90% of my code is copy/pasted directly from the docs you have pointed me at.  Per those docs I also tried binding to (gridReady) in the markup.  Doesn't work.  No Error.

Those docs are not well maintained and at times directly contradictory with themselves.

So...any other stuff I can try?

**Comment by mferster** [comment]
Hey @damonus-prime, I'm having the same issue with OnGridReady not firing when I try to use a Component as a CellRenderer. So far, the only thing that helped me was wrapping my custom method, which fetches data from the server, in a setTimeout block. I don't know why this helps, but it breaks other custom code.
Did you ever make any progress with this, or find a workaround, aside from the one in the original post? Please share. Thanks
