### ISSUE TITLE
$ag-mat-font-primary

### ISSUE THREAD

**Issue by Leonzen** [ag-grid/ag-grid-angular#188]
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question

**Current behavior**

I've upgraded from angular4 to angular5 and after trying to build the project, it has thrown me the following error:
Undefined variable: "$ag-mat-font-primary".
in C:\...\node_modules\ag-grid\src\styles\_material-legacy-var-names.scss

**What is the motivation / use case for changing the behavior?**

I've changed line 41 in "_material-legacy-var-names.scss" from:
@if variable-exists(ag-mat-primary) { $primary-color: $ag-mat-font-primary; }
to
@if variable-exists(ag-mat-primary) { $primary-color: $ag-mat-primary; }
and the build is working fine

**Please tell us about your environment:**

OS: Windows 10
IDE: Brackets & VisualStudio Code
Package manager: npm

* **ag-grid-angular version:** 

14.2.0

* **ag-Grid/ag-Grid-Enterprise version:** 

14.2.0

* **Angular version:** 

5.0.2

* **Browser:** [ Chrome XX | Firefox XX | IE XX | ]

* **Language:** [ TypeScript 2.4.2 ]

**Comment by petyosi** [comment]
This is addressed in https://github.com/ag-grid/ag-grid/commit/d4afd5aab4b80e919ec3ed63b197c06c0c76ed6c
