### ISSUE TITLE
Angular 5 AOT build error: agGridNg2.ngfactory.js is not part of the compilation output

### ISSUE THREAD

**Issue by Nandan108** [ag-grid/ag-grid-angular#190]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
- found similar issues, but closed.
```

**Current behavior**
$ ng build **-aot**

Date: 2017-12-20T15:31:00.642Z                                                            
Hash: 2dac0a20efb1f539a239
Time: 28708ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 1.18 MB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 309 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 6.97 MB [initial] [rendered]

**ERROR** in /var/www/myproject/dev/node_modules/ag-grid-angular/dist/agGridNg2.ngfactory.js
Module build failed: Error: /var/www/myproject/dev/node_modules/ag-grid-angular/dist/**agGridNg2.ngfactory.js is not part of the compilation output**. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (/var/www/myproject/dev/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:649:23)
    at plugin.done.then (/var/www/myproject/dev/node_modules/@ngtools/webpack/src/loader.js:467:39)
 @ ./src/app/product/product-detail.component.ngfactory.js 17:0-86
 @ ./src/app/product/product-detail-page.component.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts

**Expected Behavior**
No error on compile

**Minimal reproduction of the problem with instructions**
This issue started when I upgraded ag-grid from 13 to 14 and is still there at 15.

**Please tell us about your environment:**
```
$ ng -v
Angular CLI: 1.6.1
Node: 7.7.3
OS: linux x64 (Ubuntu 16.04)
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack-dev-server: 2.9.3
webpack-merge: 4.1.1
webpack: 3.10.0
```

***ag-grid-angular version:** 15.0

Could this be related to issue #182 or #184 ?

**Comment by elaijuh** [comment]
i have exactly the same error with AoT compile

nodejs 9.1.0
typescript 2.5.2
angular 5.1.2

**Comment by elaijuh** [comment]
`@ngtools/webpack@1.9.3` is released and the error message is more readable

```
Module build failed: Error: /tmp/node_modules/ag-grid-angular/dist/agGridNg2.ngfactory.js is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
```

**Comment by makinggoodsoftware** [comment]
Hi,

We can't reproduce this in our end

===============

Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
