### ISSUE TITLE
Custom Floating Filter ag-grid

### ISSUE THREAD

**Issue by ahmedmohamedma** [ag-grid/ag-grid-angular#191]
I'm submitting a ...

[x] bug report 
[ ] feature request
[ ] support request

Current behavior
- When creating a custom floating filter, when i want to search for an alphabet in filter nothing appears in the input field only numbers appeared,
while in the normal"not custom" floating filters alphabets appear normally.

Expected behavior
- the alphabets i wrote appear in the input field and filtering occurs.

Minimal reproduction of the problem with instructions

- you can check here in the example in ag-grid website
https://plnkr.co/edit/UwMKrfXSvhtNrFsioex7?p=preview
and try to write any alphabet in gold or silver column nothing will appear in the input field.

What is the motivation / use case for changing the behavior?
- Creating a custom filter based on my need.

**Please tell us about your environment:**
Operating system: Windows 10
IDE: Visual studio code
package manager: NPM

- ag-grid v13.1.2

Browser:
- all

Language:
all

**Comment by makinggoodsoftware** [comment]
Hi,

I am sorry but I dont understand how the plunkr relatest to your issue descritption, I am going to close this issue, feel free to reopen it if you have a plunkr that highlights the issue

Thanks

===============

Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
