### ISSUE TITLE
AgGridNg2: some event emitters used as inputs instead of outputs

### ISSUE THREAD

**Issue by mike-co** [ag-grid/ag-grid-angular#193]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am getting the following diagnostic logging to the console.

`ag-Grid-ng2: could not find EventEmitter: pinnedRowDataChanged`
`ag-Grid-ng2: could not find EventEmitter: rowDataUpdated`

This is probably due to having 
`@Input() public pinnedRowDataChanged: any = undefined;`
`@Input() public rowDataUpdated: any = undefined;`
which should be 
`@Output() public pinnedRowDataChanged: EventEmitter<any> = new EventEmitter<any>();`
`@Output() public rowDataUpdated: EventEmitter<any> = new EventEmitter<any>();`

**Expected behavior**
Should not have those messages.

**Minimal reproduction of the problem with instructions**
Do anything which will call those events.

**Please tell us about your environment:**
angular v 5.1.3
ag-grid-angular v 15.0.0
ag-grid v 15.0.0

**Browser:** [ all ]

**Language:** [ TypeScript 2.6.2 ]

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this - this has now been fixed and will be available in our next release.

thanks
