### ISSUE TITLE
Couldn't I use both autoGroupColumnDef and groupUseEntireRow at the same time?

### ISSUE THREAD

**Issue by MinsuLim** [ag-grid/ag-grid-angular#194]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

autoGroupColumn is disappered when I use both autoGroupColumnDef and groupUseEntireRow at the same time.

**Expected behavior**

autoGroupColumn is presented on entire row. 

**Minimal reproduction of the problem with instructions**

<ag-grid-angular style="height: 500px; width: 100%" class="ag-theme-material"
                                        [autoGroupColumnDef]="autoGroupColumnDef"
                                        [groupUseEntireRow]="true"

**What is the motivation / use case for changing the behavior?**

I want to use groupUseEntireRow function on autoGroupColumn.

**Please tell us about your environment:**

Windows7, ng cli 

* **ag-grid-angular version:** 14.2.0

* **ag-Grid/ag-Grid-Enterprise version:** 14.2.0

* **Angular version:** 5.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 63.0.3239.132

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 2.4.2

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
