### ISSUE TITLE
Make ag-grid-angular work with angular material 5

### ISSUE THREAD

**Issue by weilip1803** [ag-grid/ag-grid-angular#195]
[X ] feature request

**Current behavior**
Not working with the new angular material update. Angular material have deprecated the md-** tags and changed to mat-** tags. Changing to mat-** tags will cause ag-grid not to be displayed. 

**Expected behavior**
Hopefully ag-grid-angular can work with angular material 5

**Minimal reproduction of the problem with instructions**
clone -->https://github.com/ag-grid/ag-grid-material/tree/master/angular-material
and 
Import the relevant mat module and change any tags of the ag-grid-angular material example from a md-** tag to a mat tag in app.component html

**What is the motivation / use case for changing the behavior?**
So that ag-grid-angular can be compatible with angular material

**Please tell us about your environment:**

Windows 10, Webstorm, Angular 5.1.1, angular material 5.1.1

* **ag-grid-angular version:** 2.0.X
   "ag-grid": "^16.0.1",
    "ag-grid-angular": "^16.0.0",

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
Nill

* **Angular version:** 2.0.X
5.0.1
 "@angular/material": "2.0.0-beta.11" and "@angular/material": "5.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
   "typescript": "~2.4.2" , ES7

**Comment by YardenRon** [comment]
I got the same problem here with the following environment:

Angular 5
Angular CLI: 1.6.6
Angular material 5
Ag-grid 16.0.1

The ag-grid table is one of the main components in my team application, and unfortunately, this issue prevents us from updating our project to the newest versions of the technologies we use :(
I hope there will be a solution soon

**Comment by majhoos** [comment]
It would be ideal if someone could suggest a workaround while a fix is in progress. I am experiencing the same issue and the grid doesn't show.

**Comment by weilip1803** [comment]
@majhoos actually i realized ag-grid will work with angular material 5. But you must specifically give a height and with style eg("width: 1000px; height: 350px;) and you cannot use %. I am going to close this issue.

**Comment by lunar-safari** [comment]
This isn't working for me. I am using 

 "@angular/material": "^5.2.2",
"@angular/common": "^5.2.5",

And following this example to the letter;
https://www.ag-grid.com/angular-getting-started/

The result is 

![image](https://user-images.githubusercontent.com/35985764/37124062-d7d578b8-22ba-11e8-82ec-a87e2d4076bb.png)

Can anyone confirm that setting the width and height works?
