### ISSUE TITLE
on Click of a cell all other editable rows are turned to view mode. 

### ISSUE THREAD

**Issue by ramrealpage** [ag-grid/ag-grid-angular#196]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I could make all cells editable look at the below plunker. as soon as I click inside a cell, all other cells are made view mode. I know this is expected behavior of Ag Grid, is there a way I can retain the editable behavior of other cells.?
https://plnkr.co/edit/XbGLPZmD7pWnhd9O20iY?p=preview
**Expected behavior**

I want all editable cells (in all rows) to be in editable mode even when I click inside a cell.
is there a way I can retain the editable behavior of other cells.?
**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/XbGLPZmD7pWnhd9O20iY?p=preview

https://stackoverflow.com/questions/48822836/how-to-make-all-cells-in-ag-grid-editable-on-click-of-a-button
IDE: VS code
ag-grid: 11.0.0,
ag-grid-angular: 11.0.0,
Angular version:** 4.x
It is not an issue with the latest version. There are no examples with this kind of functionality
Chrome browser
Typescript.

**Comment by seanlandsman** [comment]
Github issues are reserved for bug reporting. For support please use either StackOverflow, or if you're a customer please contact  info@ag-grid.com for access to our support process.
