### ISSUE TITLE
Getting error while specifying cellRendererFramework component within detailCellRendererParams

### ISSUE THREAD

**Issue by mskhanse** [ag-grid/ag-grid-angular#197]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Getting following error while specifying cellRendererFramework component `"cellRendererFramework": CheckboxCellComponent` for `[detailCellRendererParams]="detailCellRendererParams"` in `ng-grid-angular` with `[masterDetail]="true"`

Below framework component is working fine for `gridOptions` but throwing error for `detailGridOptions`

> ag-grid: you are specifying a framework component but you are not using a framework version of ag-grid for : cellRenderer at ComponentResolver.getComponentToUse

```
detailCellRendererParams = {
    detailGridOptions: {
    frameworkComponents: {
        "checkboxCellComponent": CheckboxCellRenderer
      },
      columnDefs: [
        {
          "field": "isActive",
          "cellRendererFramework": CheckboxCellRenderer
        }
    ]}
};
```

Checkbox Renderer Component

```
import { Component, AfterViewInit } from '@angular/core';
import { ICellRendererAngularComp } from 'ag-grid-angular';

@Component({
  selector: 'checkbox-cell',
  template: `<mat-checkbox [ngModel]="params.value" (change)="onChange($event)"></mat-checkbox>`
}) 
export class CheckboxCellRenderer implements ICellRendererAngularComp {

  private params: ICellRendererParams;

  constructor() { }

  agInit(params: ICellRendererParams): void {
    this.params = params;
  }   

  onChange(event) {
    this.params.data[this.params.colDef.field] = event.checked;
  }

  refresh(params: ICellRendererParams): boolean {
    return true;
  }
}
```

* **ag-grid-angular version:** 16.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 16.0.1

* **Angular version:** 5.0.0

* **Language:** 
Angular
TypeScript

**Comment by mskhanse** [comment]
You can you [https://www.ag-grid.com/javascript-grid-master-detail/#providing-a-custom-detail-cell-renderer](Custom Detail Cell Renderer).

**Comment by seanlandsman** [comment]
This should work as expected now. Please upgrade and retry.

**Comment by Lazarencjusz** [comment]
@seanlandsman could you please explain the cause of this error? 
Which ag-grid version has this fix?

**Comment by acaravia** [comment]
Did anyone figure out this issue? I'm experiencing this with:

"ag-grid-community": "^20.1.0",
 "ag-grid-enterprise": "^20.1.0",
 "ag-grid-react": "^20.1.1"
