### ISSUE TITLE
Allow for using ng-template as cellRenderer

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [ag-grid/ag-grid-angular#198]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
No way to specify inline templates for cellRenderers using ng-template in Angular.

**Expected behavior**
It should be possible to reference an inline template within component's html, that would act as cellRenderer. This ng-template would have passed params as its context, so that it could reach current value, data, node, etc. It could be another property like cellRendererTemplate.

**Minimal reproduction of the problem with instructions**
- 

**What is the motivation / use case for changing the behavior?**
Oftentimes, the need for modification of how the data are rendered are somewhere between the full-blown component and valueGetter/valueTransformer. Creating new components for cellRenderers is a cumbersome and seemingly unnecessary task. There's also a question of reusability. There's little point in having separate component in filesystem, if it's used in just one place for one particular list/grid. Also, from visual point of view, disjointing the presentation between the component that actually embeds Ag-Grid, and other components that contain pieces of cell rendering, makes it harder to track and determine what will actually be rendered. It's beneficial to have all the rendering HTML templates be specified in one component HTML's file (that would contain both the component's template, as well as set of ng-templates that are used locally for that grid). 

**Please tell us about your environment:**
Irrelevant

* **ag-grid-angular version:**
16.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 
16.0.0

* **Angular version:** 
5.2.5

* **Browser:** 
All

* **Language:** 
Typescript 2.6

**Comment by koolhuman** [comment]
+1

**Comment by lterfloth** [comment]
Wasn't that possible a while ago?  People discussed it in #49

**Comment by sebastian-zarzycki-es** [comment]
Hm.. that's interesting lead, I need to check that. It still doesn't allow for using ng-template constucts in template, but it's close enough.

But I don't see this being documented anywhere. According to https://www.ag-grid.com/javascript-grid-cell-rendering/, you can only use string name of class component, the class component direct reference itself, or a function that would output rendered string. I thought cellRendererFramework property is just a shortcut for those using Angular, to put in the registered component directly, without needing additional steps to register it with AgGrid. It would be interesting to learn what cellRendererFramework is actually doing. From the link you've provided, it seems like it allows creating Angular components on the go.

**Comment by lterfloth** [comment]
I actually found a post saying they removed the functionality. Look here for further information #77. The documentation is quite confusing for me. Sometimes you just find javascript examples, even though it says angular and ometimes it's just angular1 instead of angular2.

**Comment by sebastian-zarzycki-es** [comment]
Ugh, that's a pity.

**Comment by icenold** [comment]
having to create 1 component per column is really quite a bummer if you are using cellrenderers

**Comment by seanlandsman** [comment]
Closing as this repo is now deprecated. Please feel free to raise a new issue on https://github.com/ag-grid/ag-grid if you believe this still to be an issue.
