### ISSUE TITLE
ag-grid angular custom dropdown list in custom header

### ISSUE THREAD

**Issue by ClaraBi** [ag-grid/ag-grid-angular#200]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I use ag-grid angular to build a inifinity scrolling grid, and insert my custom header into it, I added a dropdown list, but the list cannot show well because of the header height. I mean if I make the header higher, the list can show well, but not in the regular height
**Expected behavior**

but now I do not want to use the default column menu, I want to insert my dropdown list including "sorting /filtering..." items
**Minimal reproduction of the problem with instructions**

![image](https://user-images.githubusercontent.com/11343684/37560183-4d5756d2-2a0a-11e8-8a52-18a8e293f91d.png)
![image](https://user-images.githubusercontent.com/11343684/37560201-92dcea1e-2a0a-11e8-946d-efa8372c1cbe.png)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Operating system: Windows
IDE: VS official
package manager:Angular-cli
HTTP server:HTTP Module

* **ag-grid-angular version:** 2.0.X

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

"ag-grid-angular": "^16.0.0"
* **Angular version:** 2.0.X

"@angular/animations": "4.2.x",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
* **Language:**  [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by seanlandsman** [comment]
Github issues are reserved for bug reporting. For support please use either StackOverflow, or if you're a customer please contact  info@ag-grid.com for access to our support process.
