### ISSUE TITLE
agTextCellEditor not working ?

### ISSUE THREAD

**Issue by goel-sunny** [ag-grid/ag-grid-angular#203]
this.columnDefs = [ {
      editable:'true' ,
      cellEditor:'agTextCellEditor'
   }......

after doing this when i run the application cell editor is not working am i have to add  anything extra for working of this library?

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
