### ISSUE TITLE
non of cell editor is working build in or customizable.

### ISSUE THREAD

**Issue by goel-sunny** [ag-grid/ag-grid-angular#204]
In my project i have added the customise  cell editor also used build in cell editor like agtextcelleditor but non of them working , is their is also set editable = true in column defination , am i have to add something for this . 

really confused any body please suggest

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
