### ISSUE TITLE
header select all checkbox option takes all of time ?

### ISSUE THREAD

**Issue by goel-sunny** [ag-grid/ag-grid-angular#207]
hi ,

When i click on the checkbox in the header for selecting all the data , it takes alot of time to select may be because of i have large amount of  data set , can i add any overlay while it is doing selection because it feels like my screen got hanged or is their is any option to enhance its speed .

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
