### ISSUE TITLE
enabling and disabling of row editing option ?

### ISSUE THREAD

**Issue by goel-sunny** [ag-grid/ag-grid-angular#208]
Hi , 

I want to enable row cells when i select the checkbox selection feature of a particular row , is their is any such feature for row selection and enabling and disabling its cellls.

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
