### ISSUE TITLE
Function redrawRows cause memory leak

### ISSUE THREAD

**Issue by life-time** [ag-grid/ag-grid-angular#209]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When switching between rows in the table the memory increases significantly (100MB-300MB)
And sometime the garbage collection manage to release the memory but it’s take several minutes and sometime the memory not release and probably leak. 
After analysis the memory with chrome developer tools we found that the redrawRows function response to 60%-70% from memory consumption.
* note - we use redrawRows() function when data is changing 

**Expected behavior**
That the memory will be released immediately and not leak

**Please tell us about your environment:**

angular 4.46 and ag-grid-angular version 17.0.1

![memory grid api](https://user-images.githubusercontent.com/4956038/39470138-9d681c9e-4d44-11e8-9533-5567fbbc26c1.PNG)

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
