### ISSUE TITLE
agGrid periodic layout breaks async / fakeAsync tests

### ISSUE THREAD

**Issue by jonrimmer** [ag-grid/ag-grid-angular#210]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Angular's async / fakeAsync testing relies on the JS event queue eventually emptying, which it uses as a signal that all processing that could cause a test to fail has finished. E.g. all promises and observables have resolved / finished, animations have completed, etc.

However, agGrid has a `periodicallyDoLayout` function that by default runs `setTimeout` every 500 milliseconds. This means the event queue never clears, and async testing functions like `whenStable()`, `flush()` and `flushMicroTasks()` do not work. The test just spins until the framework either hits a timeout, or realises it's stuck in a polling loop, and fails.

Even worse is that there is a setting `intervalLayout` that is advertised by the docs as disabling this polling when set to a number less than or equal to zero. But it doesn't! It just reduces the resolution of the timer to to 5 seconds, meaning that event queue still never clears.

**Expected behavior**

I would suggest the following:

  - Detect when Angular is running in a testing context and automatically disable periodic layout, unless it has been explicitly enabled in the grid options.
  - Correct the documentation of the `intervalLayout` property to clarify that it can only be used to set the interval to a positive non-zero value or 5000ms, not to disable periodic layout.
  - Add a new property `suppressPeriodicLayout` to actually turn off periodic layout.

**Minimal reproduction of the problem with instructions**

Clone this repo:

https://github.com/jonrimmer/ag-grid-test

Run `npm run test`

**What is the motivation / use case for changing the behavior?**
It is impossible to test components that asynchronously load data into the agGrid component otherwise.

**Please tell us about your environment:**

macOS, VS Code, npm, Angular CLI

* **ag-grid-angular version:** 2.0.X
17.1.0

* **Angular version:** 2.0.X
5.2.0

* **Browser:**
all

* **Language:**
all

**Comment by seanlandsman** [comment]
The logic behind this has changed since. I suggest you upgrade and retry and see if the issue is resolved now.
