### ISSUE TITLE
 ag-grid-angular: Not able to get an event in cell Renderer from main component

### ISSUE THREAD

**Issue by deepender87** [ag-grid/ag-grid-angular#213]
As there is an option that we can give a call back to the component from a cell render component (via context). Reverse to this, is there any way in ag grid, which can provide the mechanism to send callback or event to the cell renderer component from the main component.? Currently i am not able to leverage the grid feature as i want to communicate to cell renderer, whenever i am trying to select/deselect a row from main component. Based on the selection/deselection of row, cellrenderer should do some action. 

Thanks

**Comment by seanlandsman** [comment]
Please refer to the documentation here: https://www.ag-grid.com/angular-more-details/#parent_child
