### ISSUE TITLE
Extra Empty Column/padding on the right even after using params.api.sizeColumnsToFit() onGridReady

### ISSUE THREAD

**Issue by avinashrd** [ag-grid/ag-grid-angular#214]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Extra White space next to the last column

**Expected behavior**

There should be no space after the last column and sizeColumnsToFit() should work seamlessly across all the browsers. Not facing this in Chrome and Firefox 

**Minimal reproduction of the problem with instructions**

I am using the Tree Data to display a group and its elements. This is an inbuilt mechanism to display group and its elements in AG Grid.
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

I am working on Windows 7
* **ag-grid-angular version:** 15.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 15.0.0

* **Angular version:** 4.3.0

* **Browser:** [IE 11]

* **Language:** [TypeScript 2.3.2]

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
