### ISSUE TITLE
Floating filter component is destroyed on horizontal scroll hence applied filters are not retained

### ISSUE THREAD

**Issue by vprasad0821** [ag-grid/ag-grid-angular#218]
**I'm submitting a ...**
```
[x] feature request
```

**Current behavior**
The documentation says the floating filters life cycle is bound to the visibility of the column. So if you hide a column (either set not visible, or horizontally scroll the column out of view) then the floating filter GUI component is destroyed. If the column comes back into view, it is created again. 

**Expected behavior**
I have Implemented custom floating filters but due to the current behavior the applied filters are removed on horizontal scroll, can the control be given to the developer on whether to allow it to destroy or retain the state through some metadata/ json configurations by which state of the filters applied 
 is retained. This will give free hands to developer to choose what behavior he/she wants.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/nXJ1CeVDCK6VWwqWcVNv?p=preview

**What is the motivation / use case for changing the behavior?**
Instead of creating a custom Header or filter from scratch developer can retain the default behavior and can extend Floating filter in order to  have the same experience when Default floating filter is used

**Please tell us about your environment:**
Windows, Web-storm, npm

* **ag-grid-angular version: 17.1.0

* **ag-Grid/ag-Grid-Enterprise version: 17.1.0

* **Angular version: 5.0.0

* **Browser:** [all]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amith-cv** [comment]
Hi, Can any one help on this regards. I am facing the same issue as well.

**Comment by KAVYA-PUJARLA** [comment]
I am also facing the same issue.Can any one help me out? Thanks in advance.

**Comment by ceolter** [comment]
when the floating filter is created, it gets passed the filter model, so it can reinstate any state into it when the column is re-displayed.

in the next version of ag-Grid (v21) that we plan to release next week, the floating filters will be changed slightly (a much better design under the hood), one of the things it will be able to do is get a reference to the owning parent filter instance. the floating filter will be free to get this instance reference and call any method it wants on it. so if you have a custom filter, you will be able to add whatever methods you want and use those methods from inside the floating filter. you could store state in the main filter on the floating filters behalf.
