### ISSUE TITLE
Support for cdkScrollable

### ISSUE THREAD

**Issue by Jamlearner** [ag-grid/ag-grid-angular#219]
Just wondering if `angular/cdkScrollable` works with ag-grid?

Sample code: 
```
<ag-grid-angular
        [columnDefs]="columnDefs"
        [gridOptions]="gridOptions"
        [rowData]="rowData"
cdkScrollable>
</ag-grid-angular>
```

**Expected behavior**
After putting `cdkScrollable` into <ag-grid-angular> tag, `cdkScrollable` should work as per usual.

**What is the motivation / use case for changing the behavior?**
I am using a contextmenu module that heavily relies on `cdkScrollable`. Reason to need `cdkScrollable` is that when scrolling in ag-grid,  I would like to close my contextmenu. Note that the contextmenu module is developed with angular/cdk.

* **ag-grid-angular version:** 14.1.0

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
