### ISSUE TITLE
TypeError: Cannot read property 'AG_GRID' of undefined.

### ISSUE THREAD

**Issue by bipinmangwani1** [ag-grid/ag-grid-angular#220]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ag-grid renders nothing and throws an error in Angular 6 prod (--prod) mode. It works fine in non-prod mode. The same code worked fine in Angular 4 with prod mode. With version 6, it shows an error in the console: **ERROR TypeError: Cannot read property 'AG_GRID' of undefined.**
[package.json.txt](https://github.com/ag-grid/ag-grid-angular/files/2093497/package.json.txt)
[package.json.txt](https://github.com/ag-grid/ag-grid-angular/files/2093498/package.json.txt)

**Expected behavior**
ag-grid should render the table.

**Minimal reproduction of the problem with instructions**
Use a very basic ag-grid table. It just won't work.
<ag-grid-angular [gridOptions]="gridOptions" class="w-100 ag-theme-material" (gridReady)="onGridReady($event)"
                         [showToolPanel]="false" [toolPanelSuppressValues]="true" [toolPanelSuppressRowGroups]="true" [toolPanelSuppressPivotMode]="true" [enableFilter]="true" [rowSelection]="'multiple'" [rowDeselection]="true" [enableColResize]="true" [overlayNoRowsTemplate]="'No Mappings to show'" [domLayout]="'domLayout'" [enableSorting]="true">
        </ag-grid-angular>

**What is the motivation / use case for changing the behavior?**
None

**Please tell us about your environment:**
Angular CLI: 6.0.0
Node: 8.11.2
OS: win32 x64
Angular: 6.0.0
... cli, common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
@ angular-devkit/architect         0.6.0
@ angular-devkit/build-angular     0.6.0
@ angular-devkit/build-optimizer   0.6.0
@ angular-devkit/core              0.6.3
@ angular-devkit/schematics        0.6.0
@ ngtools/webpack                  6.0.0
@ schematics/angular               0.6.0
@ schematics/update                0.6.0
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.6.0

* **ag-grid-angular version:** 
    "ag-grid-angular": "17.0.0",

* **ag-Grid/ag-Grid-Enterprise version:** 
    "ag-grid": "17.0.0",
    "ag-grid-enterprise": "17.0.0"

* **Angular version:** 
Angular: 6.0.0

* **Browser:** 
Chrome

* **Language:**
typescript                        2.7.2

**Comment by petkovacs19** [comment]
"buildOptimizer": true in the cli config uses [this ](https://www.npmjs.com/package/@angular-devkit/build-optimizer) package to perform further optimizations on the build. 

Updating this package to 0.6.8 resolved the issue for me or alternatively if you do not need those optimizations on your build setting that to 'false' fixes it too.

**Comment by MatellioLiyaquet** [comment]
Installing @angular-devkit/build-optimizer in dev dependencies resolved issue
Thanks

**Comment by seanlandsman** [comment]
As per the comments above, upgrade build-optimizer to resolve the issue
