### ISSUE TITLE
Two fields under same header name ag grid angular

### ISSUE THREAD

**Issue by BukicMicko** [ag-grid/ag-grid-angular#222]
**I'm submitting a  support request**

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**
Is there way to add multiple fields under same header name and also add custom input search option for Sport column? For example lets say in screenshot below for Sport column I want to add two custom buttons one after another (first button with text swimming and second button with text gymnastics). And when user click on custom input search dropdown to be open with options swimming and gymnastics. And when click on swimming only swimming to be shown in ag grid.

![image](https://user-images.githubusercontent.com/7872854/41478959-e4f38c94-70c9-11e8-885f-5d84c1e5d9d8.png)

**What is the motivation / use case for changing the behavior?**
Having ability to show multiple fields in same column (without creating column group and inside that columns).

* **ag-grid-angular version:** 17.1.0

* **Angular version:** 4.1.0

* **Browser:** all 

* **Language:** ES5

I hope that this is correct way for raising this, if not feel free to remove it immediately  :)

**Comment by seanlandsman** [comment]
Please follow the issue template
