### ISSUE TITLE
gridSizeChanged doesn't work

### ISSUE THREAD

**Issue by dloprodu** [ag-grid/ag-grid-angular#223]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The event `gridSizeChanged` doesn't work (it doesn't fire).

**Expected behavior**
This event worked fine in previous versions.

**Please tell us about your environment:**
Windows 10 and Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)

* **ag-grid-angular version:** 18.0.1

* **ag-Grid/ag-Grid-Enterprise version:** 18.0.1

* **Angular version:** 6.0.0

* **Browser:** all 

* **Language:** TypeScript 2.7.2

**Comment by etiennecrb** [comment]
It was fixed in 18.1.0 (see [changelog](https://www.ag-grid.com/ag-grid-changelog/))
