### ISSUE TITLE
RowClicked disables RowDoubleClicked

### ISSUE THREAD

**Issue by king612** [ag-grid/ag-grid-angular#224]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

An onRowClicked handler consumes the event, disabling any onRowDoubleClicked handler.

**Expected behavior**

An onRowClicked handler should not consume the event.  An onRowDoubleClicked handler should also received a RowDoubleClicked event, but it does not.

**Minimal reproduction of the problem with instructions**
Add the two handlers on the same grid.  The double clicked handler will never fire.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
CentOS running recent version of Chrome

* **ag-grid-angular version:** 2.0.X
18.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **Angular version:** 2.0.X
5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
