### ISSUE TITLE
Binding data to ag-grid when i pass it from subcomponent

### ISSUE THREAD

**Issue by harishaw** [ag-grid/ag-grid-angular#225]
I have a angular 2/4 ag-grid-angular component which is showing up the grid. (say Component A)
Subsequently i have component B and component C.
I am resetting the data on click and my Component C contains that reset button.
So on click i am using event emitter and emitting the data to component B because i have UI structure to be used there in component B.
Now from B component i need to update the grid data on reset and set to default . I am calling the service and getting the data in an array. but it is not binding to rowData.
Please help me how to set the data again on reset.

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
