### ISSUE TITLE
Module not found: Error: Can't resolve 'ag-grid/main'

### ISSUE THREAD

**Issue by GuerrillaCoder** [ag-grid/ag-grid-angular#240]
I am using :

>"ag-grid-angular": "19.0.0",
>"ag-grid-community": "19.0.0",
> Angular 6 CLI

I was using version 18 before and everything was working fine.  I upgraded to latest version and if I run `ng serve` my app runs fine but when I try to run `ng build --prod` I get the following errors:

```
ERROR in ./node_modules/ag-grid-angular/dist/ng2FrameworkComponentWrapper.js
Module not found: Error: Can't resolve 'ag-grid' in 'E:\Clients\Turma\SEODomainAuction\SEODomainAuction\SEODomainAuction\node_modules\ag-grid-angular\dist'
ERROR in ./node_modules/ag-grid-angular/dist/agGridNg2.js
Module not found: Error: Can't resolve 'ag-grid' in 'E:\Clients\Turma\SEODomainAuction\SEODomainAuction\SEODomainAuction\node_modules\ag-grid-angular\dist'
ERROR in ./node_modules/ag-grid-angular/dist/ng2FrameworkComponentWrapper.js
Module not found: Error: Can't resolve 'ag-grid/main' in 'E:\Clients\Turma\SEODomainAuction\SEODomainAuction\SEODomainAuction\node_modules\ag-grid-angular\dist'
ERROR in ./node_modules/ag-grid-angular/dist/ng2FrameworkFactory.js
Module not found: Error: Can't resolve 'ag-grid/main' in 'E:\Clients\Turma\SEODomainAuction\SEODomainAuction\SEODomainAuction\node_modules\ag-grid-angular\dist'
```

Is there a way to get this working or should I downgrade?

**Comment by GuerrillaCoder** [comment]
New community module just doesn't seem to be working with angular.

Working versions:

    "ag-grid": "18.1.2",
    "ag-grid-angular": "18.1.0",

**Comment by seanlandsman** [comment]
ag-grid was renamed to ag-grid-community in version 19.

change the name in your dependencies and it should work

**Comment by hocine15** [comment]
I have the same kind of issue with ag-grid 19.1.0, tested with all 19.x.x versions but got same problem like Can't resolve 'ag-grid/main' issues seems lot of modules not found !!!

**Comment by seanlandsman** [comment]
@hocine15 https://github.com/ag-grid/ag-grid-angular-cli-example uses the cli to build a prod build that includes AOT
