### ISSUE TITLE
Angular 7 issue

### ISSUE THREAD

**Issue by alfonsserra** [ag-grid/ag-grid-angular#241]
After upgrading to Angular 7, everything is working fine in the development environment,  but once I build the application for production with "ng build --prod" the grid is not rendered and a "Cannot read property 'create' of undefined" exception error is fired. 

The same exception error is fired despite the version, as I have tested versions 16.x.x, 17.x.x, 18.x.x and 19.x.x.

The issue seems related to the minification phase in Terser. In fact if I use @angular-devkit/build-angular 0.6.7, works great.

**Comment by seanlandsman** [comment]
This repo is now deprecated - please raise issues in ag-grid/ag-grid 

https://github.com/seanlandsman/ag-grid-angular-7 demonstrates using ag-Grid and Angular 7

**Comment by changhuixu** [comment]
@seanlandsman why did you move this repo out of ag-grid official account? I am just curious..

**Comment by seanlandsman** [comment]
@changhuixu we've moved to a monorepo setup for ag-Grid and its associated sub modules/projects

**Comment by andrejnsimoes** [comment]
@alfonsserra did you solve this one?

**Comment by yogavigneshwaran** [comment]
I have updated the ag grid version from 17 to 20. It works fine.
