### ISSUE TITLE
Error: Cannot set property 'dynamicParams' of null

### ISSUE THREAD

**Issue by umangsavaliya** [ag-grid/ag-grid-angular#242]
**I'm submitting a ...**  bug
```
[x] bug report => search github for a similar issue or PR before submitting
[] feature request
[] support request
```

**Current behavior**

Trying to use "cellEditorSelector" with Angular 6.
created one custom editor and want to open that editor for specific condition.
OnCell edit, m getting Error: Cannot set property 'dynamicParams' of null
Issue reproduce @ below stackblitz link
https://stackblitz.com/edit/angular-ag-grid-angular-urehq2

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-angular version:** 2.0.X

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **Angular version:** 6.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
You should be using this.gridOptions.frameworkComponents for angular components

**Comment by bndivya** [comment]
Hello.. 

How can we use gridOptions.frameworkComponents for angular components which have certain services as dependencies.

Below is the code snippet.
 gridOptions: GridOptions = {
    frameworkComponents:{
      'cellRenderer1': cellRendererComponent1,
      'cellRenderer2': cellRendererComponent2
    }
  };

export class cellRendererComponent1 {
  constructor(public cellRendererService1: cellRendererService1) {}
 .....
}

export class cellRendererComponent2 {
  constructor(public cellRendererService2: cellRendererService2) {}
 .....
}

I get this following error:
error TS2322: Type '{ frameworkComponents: { 'cellRenderer1': type...' is not assignable to type 'GridOptions'.
  Types of property 'frameworkComponents' are incompatible.
    Type '{ 'cellRenderer1': typeof CellRendererComponent1; 'cellRenderer2': typeof cellRe...' is not assignable to type '{ [p: string]: new () => any; }'.
      Property ''cellRenderer1'' is incompatible with index signature.
        Type 'typeof cellRendererComponent1' is not assignable to type 'new () => any'.

Is there a way to mention the dependencies or is there any other way to resolve this issue?
