### ISSUE TITLE
Grid not updating after using setColumnDefs to hide columns

### ISSUE THREAD

**Issue by dmacfarlane** [ag-grid/ag-grid-angular#243]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

A call to `api.setColumnDefs()` to hide columns does not update the grid.

**Expected behavior**

A call to `api.setColumnDefs()` to hide columns should update the grid.

**Minimal reproduction of the problem with instructions**

This behavior is working with ag-grid-angular 19.0.0 and not with 19.1.1.

Stackblitz example using 19.0.0 where the hide button is working: 

  https://stackblitz.com/edit/ag-grid-angular?file=package.json

Change the package.json version to 19.1.1, ctrl-s to save, and the hide button will no longer work.

**Comment by dmacfarlane** [comment]
Issue is being tracked here: https://github.com/ag-grid/ag-grid/issues/2771

**Comment by afarnes** [comment]
It's a bug.  Set setColumnDefs to blank array then call api.setColumnDefs() then reset setColumnDefs to new array then call api.setColumnDefs()

this.columnDefs = [];
this.gridOptions.api.setColumnDefs(this.columnDefs);
this.columnDefs.push(
          {
              headerName: 'col1',
              field: 'col1',
              hide: true
          }, {
              headerName: 'col2',
              field: 'col2',
              hide: false
          }
         )
this.gridOptions.api.setColumnDefs(this.columnDefs);

**Comment by kristian2x** [comment]
Is this for real ag-grid? This seems very hacky..
Any update on this?
thanks,
a potential customer
