### ISSUE TITLE
Update deps for Angular 8

### ISSUE THREAD

**Issue by MicMicMon** [ag-grid/ag-grid-angular#262]
`ng update --all` prevents some updates because of the `ag-grid` package's deps:

```
Package "ag-grid-angular" has an incompatible peer dependency to "core-js" (requires "^2.4.1", would install "3.1.3")
Package "ag-grid-angular" has an incompatible peer dependency to "core-js" (requires "^2.4.1", would install "3.1.3").
```
Would it be possible to update the dependencies?

**Comment by jpike88** [comment]
@seanlandsman can we please have this done sooner rather than later? It's pretty fast to do, and ag-grid works fine in angular 8.

**Comment by jpike88** [comment]
@seanlandsman hi, I've been using this in production and it's working fine.

I'd like to stop seeing these in my install logs, angular 8 has been out for a while now, could you guys please fix this.

ag-grid-angular@21.0.0 requires a peer of @angular/compiler-cli@>=2.1.x but none is installed. You must install peer dependencies yourself.
npm WARN ag-grid-angular@21.0.0 requires a peer of core-js@^2.4.1 but none is installed. You must install peer dependencies yourself.

**Comment by seanlandsman** [comment]
This will be updated in our patch release, due today

thanks

**Comment by jpike88** [comment]
@seanlandsman my issue was only half done.

```ag-grid-angular@21.0.1 requires a peer of core-js@>=2.4.1 but none is installed```

https://github.com/ag-grid/ag-grid/blob/47b7e31fedc525d33abfe37aa197e65f35b86d87/packages/ag-grid-angular/package.json#L64

I'm still getting this error. As I specified in my ticket submission in your helpdesk, some developers may prefer not to use core-js at all, it's just a polyfill library. This library should not be opinionated about what kind of polyfill library to use as a peer dependency, and leave that choice to the developer. I don't _want_ to use core-js, and I don't _need_ to use core-js in order for ag-grid-angular to function properly.

**Comment by Rakesh-Sorathiya** [comment]
Hello @seanlandsman, 

is ag-grid have full compatibility with angular 8.0 version?

Thank You.

**Comment by seanlandsman** [comment]
Yes, Angular 8 is supported.
