### ISSUE TITLE
How to use a Angular2 component to render the child node of a column (with a cellRenderer: 'group')?

### ISSUE THREAD

**Issue by phillipebarbosa** [ag-grid/ag-grid-angular#79]
Hi,

When setting a cell group (*cellRenderer: 'group'*), is there any way to use a Angular2 component to render just the child node of this column? Setting the *cellRendererFramework* property makes me handle parent and child node expand/collapse by myself. Also, if a set the *groupRowInnerRendererFramework* property, I'll have to handle all the columns (parents and childs) of the grid, and I'd like to use the Angular2 component to render the child node of just one column.

Thanks!

**Comment by ceolter** [comment]
no way to do this currently. thanks for raising, we missed this scenario. we'll allow innerRenderers to be ng2, hopefully we implement it soon.

**Comment by roski** [comment]
+1

**Comment by zemskovmm** [comment]
+ 1

**Comment by 1-0-1** [comment]
+1

**Comment by elineopsommer** [comment]
+1

**Comment by seanlandsman** [comment]
AG-380 covers this our side - it should be included in our next release

You can track its progress on our pipe line page here: https://www.ag-grid.com/ag-grid-pipeline/

thanks

**Comment by kgfaith** [comment]
Anything update on this please? Can't find, AG-380 on pipe line page.
